name: invest3141
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel
  - numpy
  - pandas
  - scipy
  - rpy2
  - r-base
  - r-rgdal
  - r-raster
  - r-sp
  - r-terra
  - r-proj4
  - r-irkernel
  - gdal==3.5.3
